name: NODEJS CICD Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Install dependencies
          run: npm install
    
    hello:
        runs-on: ubuntu-latest  # You need to specify the environment for this job
        steps:
        - name: All good
          run: echo "All good"  # Correct syntax for running commands in steps
